apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: default
  labels:
    app: catalog
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
  namespace: default
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - image: simas/catalog:8
          name: catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512M"
              cpu: "200m"
            limits:
              memory: "1G"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10